[build]
  command = "cd curved-cluster && npm install && npm run build && cp -r ../index.html ../an_carte.html ../calc.html ../calculateur.html ../robots.txt ../Blogs ../Leads ../Realisations ../Teko ../almarena-neue-font-family ../css ../helvetica-neue ../icons ../images ../img_pub ../js ../partenaire ./dist/ && node ../generate-sitemap.js"
  publish = "curved-cluster/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirections pour s'assurer que les fichiers statiques à la racine fonctionnent correctement
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {path = ["/*.html"], except = ["/curved-cluster/*"]}

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-0.xml"
  status = 301
  force = true

# Paramètres pour le domaine personnalisé
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Configuration HTTPS et sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"