[build]
  command = "cd curved-cluster && npm install && npm run build && cp -r ../index.html ../an_carte.html ../calc.html ../calculateur.html ../robots.txt ../Blogs ../Leads ../Realisations ../Teko ../almarena-neue-font-family ../css ../helvetica-neue ../icons ../images ../img_pub ../js ../partenaire ./dist/ && node ../generate-sitemap.js"
  publish = "curved-cluster/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirections pour s'assurer que les fichiers statiques à la racine fonctionnent correctement
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {path = ["/*.html"], except = ["/curved-cluster/*"]}

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-0.xml"
  status = 301
  force = true

# Paramètres pour le domaine personnalisé
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Configuration HTTPS et sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    # Activer explicitement la compression Brotli et Gzip
    Accept-Encoding = "br, gzip"
    # Optimiser la mise en cache par défaut
    Cache-Control = "public, max-age=86400"

# Configuration de compression spécifique pour les fichiers texte
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    # Assurer que la compression est prioritaire pour HTML
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

# Compression des polices
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression des images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

# Configuration de compression pour JSON
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    Vary = "Accept-Encoding"